version: "3.6"
services:
  araf.aljami.me:
    image: 'game.aljami.me-sokoban-defold:latest'
    ports:
      - '3002:3000'
    networks:
      - game.aljami.me
networks:
  # Declare our private network.  We must declare one for the magic
  # Docker DNS to work, but otherwise its default settings are fine.
  game.aljami.me: {}