trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'ajami1331.azurecr.io'
      repository: 'game.aljami.me-sokoban-defold'
      command: 'buildAndPush'
      Dockerfile: '$(System.DefaultWorkingDirectory)/Sokoban_defold/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

  - task: Bash@3 
    displayName: "Creating build staging directory structure"
    inputs:
      targetType: 'inline'
      script: |
        ls $(System.DefaultWorkingDirectory)
        ls $(Build.StagingDirectory)
        mkdir -p $(Build.StagingDirectory)/Sokoban_defold/

  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Visual Studio Enterprise Subscription(fd24d692-fa14-4ae1-bc9c-b6bd3c64d6d0)'
      azureContainerRegistry: '{"loginServer":"ajami1331.azurecr.io", "id" : "/subscriptions/fd24d692-fa14-4ae1-bc9c-b6bd3c64d6d0/resourceGroups/araf-build-agents/providers/Microsoft.ContainerRegistry/registries/ajami1331"}'
      dockerComposeFile: '$(System.DefaultWorkingDirectory)/Sokoban_defold/docker-compose.yml'
      projectName: 
      action: 'Lock services'
      outputDockerComposeFile: '$(Build.StagingDirectory)/Sokoban_defold/docker-compose.yml'
  
  - task: CopyFiles@2
    displayName: 'Copy Files to artifact staging directory'
    inputs:
      SourceFolder: '$(Build.StagingDirectory)/Sokoban_defold'
      Contents: 'docker-compose.yml'
      TargetFolder: $(Build.ArtifactStagingDirectory)/Sokoban_defold

  - upload: $(Build.ArtifactStagingDirectory)/Sokoban_defold
    artifact: Sokoban_defold
