name: Sokoban - raylib -c - Web
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'raylib_c/**'
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: ./raylib_c
          file: ./raylib_c/Dockerfile
          push: false
          tags: raylib-c-web:latest
      - run: |
          ./raylib_c/scripts/get-package-from-docker-container.sh raylib-c-web:latest ./releases/
          ls ./releases/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./releases
          destination_dir: sokoban-raylib-c
