name: Sokoban - raylib -c - Web
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'raylib_c/**'
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: ./raylib_c
          file: ./raylib_c/Dockerfile
          push: false
          tags: raylib-c-web:latest
      - run: |
          ./raylib_c/get-package-from-docker-container.sh raylib-c-web:latest ./releases/
          ls ./releases/
